### ISSUE TITLE
Shopping page discussion

### ISSUE THREAD

**Issue by jasontsh** [sherrychen1120/XpressCart#1]
Need to know the following, in order of urgency:
- [x] List adding format- how is the newly scanned item added to the shopping list: is it added at the top or at the bottom of the list?  
- [x] How are we hard-coding the items?  Right now my plan is to just have the barcode there only, just for debugging.  Also need to know how the shopping list item's design: do we have a photo next to the name and price and weight or what?
- [x] Full design of the entire page, with colors and pixels and everything

**Comment by sherrychen1120** [comment]
![slide1](https://cloud.githubusercontent.com/assets/16065362/13696696/22d7d9ea-e736-11e5-8b30-c7e3b65439ac.jpg)
![slide2](https://cloud.githubusercontent.com/assets/16065362/13696697/22d9f1bc-e736-11e5-880a-56e9e462d0ac.jpg)
![slide3](https://cloud.githubusercontent.com/assets/16065362/13696698/22da3618-e736-11e5-8c23-e86c6199e82f.jpg)

Above are the photos for the landing page and shopping page

**Comment by sherrychen1120** [comment]
rgb:
page one: 
dark green: R 38, G 78, B 31 264E1F
background: R 226, G 222, B 211 E2DED3 

page two & three:
dark green: R 38, G 78, B 31  264E1F
list background & keyboard background (light green): R 241, G 245, B 218 F1F5DA
recommendation background (middle green): R 85, G 157, B 63 559D3F
button: R 192, G 213, B 58  C0D53A

**Comment by jasontsh** [comment]
The third page is key-in-code interface, where the 10 buttons are going to be ordered as 1-2-3 4-5-6 7-8-9, 0

**Comment by sherrychen1120** [comment]
Updated design:
Login page: [keep the skip button] [add the four corners in the camera scanning area if possible]
![slide1](https://cloud.githubusercontent.com/assets/16065362/13719247/d315fbea-e7c0-11e5-83fd-2e749eae9283.jpg)

First-item scanning page: [Same as the next one, just change the text on the right] [add the four corners in the camera scanning area if possible]
![slide2](https://cloud.githubusercontent.com/assets/16065362/13719254/f6cce418-e7c0-11e5-912e-e1ad5fd24454.jpg)

Item-scanning mode page: [add the four corners in the camera scanning area if possible]
![slide3](https://cloud.githubusercontent.com/assets/16065362/13719257/0945fe90-e7c1-11e5-8585-f8c919ecc042.jpg)

Recommendation mode page: [after the user click on one of the recommendations]
![slide4](https://cloud.githubusercontent.com/assets/16065362/13719266/26c969a2-e7c1-11e5-96ce-ac36f356cf3c.jpg)

Remove-item mode page: [after the weighing scale sense a reduction in the weight] [After the user scan the item, the app will confirm the weight with the scale. If correct then change back to the item-scanning mode page. If incorrect... leave it till later, we won't need it in the video]
![slide5](https://cloud.githubusercontent.com/assets/16065362/13719270/3d4e881a-e7c1-11e5-8a14-da069464dbb5.jpg)

Key-in-item-code mode page: [after the user click on "key in item code"] [pls make keyboard buttons rectangular]
![slide6](https://cloud.githubusercontent.com/assets/16065362/13719287/915f0772-e7c1-11e5-8bab-f941ea504faf.jpg)

Payment-scanning page: [after the user click on "finish & pay"]
![slide7](https://cloud.githubusercontent.com/assets/16065362/13719299/b7cf6ae6-e7c1-11e5-9e32-7f7972462522.jpg)

Payment-confirmation page: [after the user successfully scan his/her credit card]
![slide8](https://cloud.githubusercontent.com/assets/16065362/13719347/3e80e98e-e7c2-11e5-9f15-21b8029226dc.jpg)

Final page: [after the user sign his/her name and click on "OK"]
![slide9](https://cloud.githubusercontent.com/assets/16065362/13719349/44ddfdda-e7c2-11e5-9a01-5d74c6b5ee8b.jpg)

[If the user click on "Finish", change back to the first page]

**Comment by sherrychen1120** [comment]
Design Updated:
Since card.io doesn't have the signature part included, change it to CVV? [this would need to include a keyboard... lol] A possible design attached below:
![slide8 - 2](https://cloud.githubusercontent.com/assets/16065362/13720526/2170feda-e7d9-11e5-976a-9eb11a27e64c.jpg)

**Comment by jasontsh** [comment]
We will know their cvv.  We will know basically everything we need for a transaction without the signature.

**Comment by sherrychen1120** [comment]
Design update: 
Unsanned items: [Error message for un-scanned items in the cart]
![slide03](https://cloud.githubusercontent.com/assets/16065362/13722212/a5ed283c-e80b-11e5-8ef7-ccfb14c15630.jpg)

Payment page: [Enter zip code]
![slide11](https://cloud.githubusercontent.com/assets/16065362/13722223/db46e126-e80b-11e5-8ed3-1d3c419b2aa4.jpg)

**Comment by jasontsh** [comment]
FYI, if there are any changes, let's start a new issue or use other issues.

**Comment by sherrychen1120** [comment]
![confirmation page](https://cloud.githubusercontent.com/assets/16065362/13835409/03e48546-ebce-11e5-8640-4abb712078c4.jpg)

**Comment by sherrychen1120** [comment]
![key in code page](https://cloud.githubusercontent.com/assets/16065362/13857908/6ce2d622-ec52-11e5-9f0c-ce8102c187e1.jpg)

**Comment by jasontsh** [comment]
Prototype done.
